name: Node Script & Upload Output

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred version
        

      - name: Clone private repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://itzkunikazu07:${TOKEN}@github.com/itzkunikazu07/Files.git
          npm install xmlbuilder instagram-url-direct
          node index.js
          
      - name: Push files
        uses: ad-m/github-push-action@v5
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: main
          force: true
          message: "Add files"
          files: rss_feed.xml,rss_feed.xml
