name: Node Script & Upload Output

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred version

      - name: Install dependencies
        run: npm install xmlbuilder instagram-url-direct

      - name: Run Node script
        run: node index.js
        

      - name: Clone private repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://itzkunikazu07:${TOKEN}@github.com/itzkunikazu07/Files.git

      - name: Configure git for PAT
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit files
        run: |
          git add rss_feed.xml history.json
          git commit -m "Add output files generated by workflow" || echo "No changes to commit"

      - name: Push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://itzkunikazu07:${TOKEN}@github.com/itzkunikazu07/RSS.git
          git push origin main
